# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 259d8b135cb6d6a62a12c3c3c44ba5bde843f56b6893918c7b4db3f5ff329ff9f91f97bb4a8d93dc328f1adb4e7be5eff5ce39711e5c12e62a6e5699056a73d5

test:
  secret_key_base: 42bb4965f1154d07d07640f78063815421933aea2bf36f10ffcbe830df308c889975de6d80cabd83725bc564a10a173899675011044b4029be3ee961a11babf5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
